/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.kris.jlr.r1000.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.kris.jlr.r1000.model.R1000;
import com.liferay.kris.jlr.r1000.service.R1000LocalServiceUtil;

/**
 * The extended model base implementation for the R1000 service. Represents a row in the &quot;JLR_R1000&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link R1000Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see R1000Impl
 * @see R1000
 * @generated
 */
@ProviderType
public abstract class R1000BaseImpl extends R1000ModelImpl implements R1000 {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a r1000 model instance should use the {@link R1000} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			R1000LocalServiceUtil.addR1000(this);
		}
		else {
			R1000LocalServiceUtil.updateR1000(this);
		}
	}
}